AutoThemeSwitchingEnabled: true
Governor: NightLight
Autostart:
  Validate: true
WindowsThemeMode:
  Enabled: false
  DarkThemePath: C:\WINDOWS\Resources\Themes\dark.theme
  LightThemePath: C:\WINDOWS\Resources\Themes\aero.theme
  MonitorActiveTheme: false
  ApplyFlags: []
AppsSwitch:
  Enabled: true
  Component:
    Mode: Switch
SystemSwitch:
  Enabled: true
  Component:
    Mode: Switch
    TaskbarSwitchDelay: 1200
    TaskbarColorSwitch: true
    TaskbarColorDuring: Dark
    DWMPrevalenceSwitch: true
    DWMPrevalenceEnableTheme: Light
TouchKeyboardSwitch:
  Enabled: false
  Component: {}
ColorizationSwitch:
  Enabled: true
  Component:
    LightHex: '#FFA95F60'
    DarkHex: '#FFB85755'
    LightAutoColorization: true
    DarkAutoColorization: true
ColorFilterSwitch:
  Enabled: true
  Component: {}
CursorSwitch:
  Enabled: true
  Component:
    CursorsLight: Windows Inverted
    CursorsDark: Windows Inverted
Sunrise: 2024-03-10T07:00:00.0000000
Sunset: 2024-03-10T20:00:00.0000000
Location:
  PollingCooldownTimeSpan: 1.00:00:00
  Enabled: false
  UseGeolocatorService: false
  SunsetOffsetMin: 0
  SunriseOffsetMin: 0
  CustomLat: 0
  CustomLon: 0
Tunable:
  BatterySliderDefaultValue: 25
  DwmRefreshViaColorization: false
  UseLogonTask: false
  Debug: true
  Trace: false
  DebugTimerMessage: false
  ShowTrayIcon: true
  UICulture: en
GPUMonitoring:
  Enabled: false
  Threshold: 30
  Samples: 1
ProcessBlockList:
  ProcessNames: []
  Enabled: false
Events:
  DarkThemeOnBattery: true
  Win10AllowLockscreenSwitch: false
Notifications:
  OnAutoThemeSwitching: true
  OnSkipNextSwitch: true
AutoSwitchNotify:
  Enabled: false
  GracePeriodMinutes: 5
Hotkeys:
  Enabled: false
  ForceLight:
  ForceDark:
  NoForce:
  ToggleTheme:
  TogglePostpone:
  ToggleAutoThemeSwitch:
IdleChecker:
  Enabled: false
  Threshold: 5
WallpaperSwitch:
  Enabled: true
  Component:
    TypeLight: Individual
    TypeDark: Individual
    Position: Fill
    GlobalWallpaper:
      Light: C:\Users\mrcra\AppData\Roaming\johnsadventures.com\Background Switcher\ActiveBackground.jpg
      Dark: C:\Users\mrcra\AppData\Roaming\johnsadventures.com\Background Switcher\ActiveBackground.jpg
    SolidColors:
      Light: '#FFFFFF'
      Dark: '#000000'
    Monitors:
    - Id: \\?\DISPLAY#AUO2992#5&17b6495&0&UID256#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7}
      LightThemeWallpaper: C:\WINDOWS\SystemApps\MicrosoftWindows.Client.CBS_cw5n1h2txyewy\DesktopSpotlight\Assets\Images\image_1.jpg
      DarkThemeWallpaper: C:\Users\mrcra\AppData\Roaming\johnsadventures.com\Background Switcher\ActiveBackground.jpg
Updater:
  AutoInstall: false
  Enabled: true
  Silent: false
  DaysBetweenUpdateCheck: 7
  CheckOnStart: true
  VersionQueryUrl: https://raw.githubusercontent.com/AutoDarkMode/AutoDarkModeVersion/master/version-beta.yaml
  DownloadBaseUrl:
  ZipCustomUrl:
  HashCustomUrl:
