
# Wait x milliseconds for starship to check files under the current directory.
command_timeout = 1111
scan_timeout    = 1000

[line_break]
disabled = false

[directory]
format            = "[$path]($style)[$read_only]($read_only_style) "
truncate_to_repo  = false
truncation_length = 4
truncation_symbol = "â€¦/"

[directory.substitutions]
"Documents" = "ïœ˜ "
"Downloads" = "ï€™ "
"Music"     = "ï€ "
"Pictures"  = "ï€¾ "
"global"    = "ğŸŒ"
"nixos"     = "â„ï¸ "
"~/.dots"   = "Â°Â°Â°"

[package]
disabled = true

[cmd_duration]
min_time           = 1000
show_notifications = true

[time]
# disabled = true
format          = 'ğŸ•™[ $time ]($style)'
time_format     = "%H:%M"
time_range      = '22:00:00-07:00:00'
utc_time_offset = "-5"

[shell]
disabled = true

[status]
# disabled = true
format     = '[$symbol $common_meaning$signal_name$maybe_int]($style) '
map_symbol = true
symbol     = "ğŸ”´"

[character]
error_symbol   = "ğŸš©"
success_symbol = "ğŸš€"

[battery]
charging_symbol    = "âš¡ï¸ "
discharging_symbol = "ğŸ’€ "
full_symbol        = "ğŸ”‹ "

[sudo]
allow_windows = true
style         = "bold green"
symbol        = "ğŸ‘©â€ğŸ’» "
# disabled = true

[git_status]
# disabled = true
ahead      = "ğŸğŸ’¨"
behind     = "ğŸ˜°"
conflicted = "ğŸ³"
deleted    = "ğŸ—‘"
diverged   = "ğŸ˜µ"
modified   = "ğŸ“"
renamed    = "ğŸ‘…"
staged     = '[++\($count\)](green)'
stashed    = "ğŸ“¦"
untracked  = "ğŸ¤·â€"
up_to_date = "âœ“"
